oro_entity_config:
    extend:
        entity:
            grid_action:
                -                           {"name":"Unique Key", "route":"oro_entityextend_entity_unique_key", "type":"redirect", "icon":"th-large",  "acl_resource":"root", "args":["id"]}
            layout_action:                  ~
    #            -                           {"name":"Create", "route":"oro_entityconfig_create", "title":"Create custom entity"}
            items:
                owner:
                    priority:               40
                    default_value:          'System'
                    required:               true
                    grid:
                        type:               string
                        label:              'Type'
                        filter_type:        oro_grid_orm_string
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                    form:
                        type:               text
                        block:              entity
                        options:
                            read_only:      true
                            required:       false
                            label:          'Type'



                is_extend:
                    required:               true

                extend_class:
                    required:               true

                proxy_class:
                    required:               true

        field:
            grid_action:
                -                           {'name':'Remove', 'route':'oro_entityextend_field_remove', 'type':'redirect', 'icon':'trash', 'acl_resource':'root', 'filter':'is_extend', 'args':['id']}
            layout_action:
                -                           {'name':'Create Field', 'route':'oro_entityextend_field_create', 'entity_id':true, 'filter':'is_extend'}
            items:
                owner:
                    priority:               20
                    default_value:          'System'
                    required:               true
                    grid:
                        type:               string
                        label:              'Type'
                        filter_type:        oro_grid_orm_string
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false
                    form:
                        type:               text
                        options:
                            read_only:      true
                            required:       false
                            label:          'Type'


                is_extend:
                    required:               true
#                    grid:
#                        type:               boolean
#                        label:              'Is Extend Field'
#                        filter_type:        oro_grid_orm_boolean
#                        required:           true
#                        sortable:           true
#                        filterable:         true
#                        show_filter:        true
#                    form:
#                        type:               choice
#                        options:
#                            choices:        ['No', 'Yes']
#                            read_only:      true
#                            required:       false
#                            label:          "Is Extend Field"
