oro_entity_config:
    scope:                              extend

    entity:
        grid_action:
            -                           {"name":"View",   "route":"oro_entityconfig_view",   "type":"redirect", "icon":"book",    "acl_resource":"root", "filter":"is_extend", "args":["id"]}
            -                           {"name":"Update", "route":"oro_entityconfig_update", "type":"redirect", "icon":"edit",    "acl_resource":"root", "filter":"is_extend", "args":["id"]}
            -                           {"name":"Fields", "route":"oro_entityconfig_fields", "type":"redirect", "icon":"th-list", "acl_resource":"root", "filter":"is_extend", "args":["id"]}
        layout_action:                  ~
#            -                           {"name":"Create", "route":"oro_entityconfig_create", "title":"Create custom entity"}
        items:
            is_extend:
                required:               true
                grid:
                    type:               boolean
                    label:              'Is Extend Entity'
                    filter_type:        oro_grid_orm_boolean
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               choice
                    options:
                        choices:        ['No', 'Yes']
                        read_only:      true
                        required:       false
                        label:          "Is Extend Entity"

            extend_class:
                required:               true

            proxy_class:
                required:               true

    field:
        grid_action:
            -                           {"name":"View",   "route":"oro_entityextend_field_view",   "type":"redirect", "icon":"file", "acl_resource":"root", "filter":"is_extend", "args":["id"]}
            -                           {"name":"Update", "route":"oro_entityextend_field_update", "type":"redirect", "icon":"edit",   "acl_resource":"root", "filter":"is_extend", "args":["id"]}
            -                           {"name":"Remove", "route":"oro_entityextend_field_remove", "type":"delete",   "icon":"trash",  "acl_resource":"root", "filter":"is_extend", "args":["id"]}
        layout_action:
            -                           {"name":"Create", "route":"oro_entityextend_field_create", "entity_id":true}
            -                           {"name":"Back",   "route":"oro_entityconfig_index", "aClass":"btn-info", "title":"Back to Enteties grid"}
        items:
            is_extend:
                required:               true
                grid:
                    type:               boolean
                    label:              'Is Extend Field'
                    filter_type:        oro_grid_orm_boolean
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               choice
                    options:
                        choices:        ['No', 'Yes']
                        read_only:      true
                        required:       false
                        label:          "Is Extend Field"


