oro_entity_config:
    extend:
        entity:
            items:
                owner:
                    options:
                        priority:           40
                        internal:           true
                        default_value:      'System'
                    grid:
                        type:               string
                        label:              'Type'
                        filter_type:        oro_grid_orm_string
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                    form:
                        type:               text
                        block:              entity
                        options:
                            read_only:      true
                            required:       false
                            label:          'Type'
                    view:
                        type:               string
                        stats:              false
                        block:
                is_extend:
                    options:
                        default_value:      false
                        internal:           true
                state:
                    options:
                        priority:           25
                        default_value:      ''
                        internal:           true
                    grid:
                        type:               string
                        label:              'Status'
                        filter_type:        oro_grid_orm_choice
                        choices:            {system: '', new: 'New', active: 'Active', updated: 'Updated', deleted: 'To be deleted'}
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false
                extend_class:
                    options:
                        internal:           true
                unique_key:
                    options:
                        internal:           true
                        serializable:       true
                proxy_class:
                    options:
                        internal:           true

        field:
            grid_action:
                -                           {'name':'Remove', 'route':'oro_entityextend_field_remove', 'type':'delete', 'icon':'trash', 'acl_resource':'root', 'filter':'is_extend', 'args':['id']}
            layout_action:
                -                           {'name':'Manage unique keys', 'route':'oro_entityextend_entity_unique_key', 'entity_id':true}
                -                           {'name':'Create field', 'route':'oro_entityextend_field_create', 'entity_id':true, 'filter':'is_extend'}
                -                           {'name':'Update schema', 'route':'oro_entityextend_update', 'entity_id':true, 'aClass':'btn-danger entity-extend-apply'}
            items:
                owner:
                    options:
                        priority:           20
                        default_value:      'System'
                    grid:
                        type:               string
                        label:              'Type'
                        filter_type:        oro_grid_orm_string
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false

                state:
                    options:
                        priority:           25
                        default_value:      ''
                    grid:
                        type:               string
                        label:              'Status'
                        filter_type:        oro_grid_orm_choice
                        choices:            { new: 'New', applied: 'Applied', updated: 'Updated', deleted: 'To be deleted'}
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false

                is_extend:
                    options:
                        priority:           40
                        default_value:      false
                        is_bool:            true
#                    grid:
#                        type:               boolean
#                        label:              'Is Extend Field'
#                        filter_type:        oro_grid_orm_boolean
#                        required:           true
#                        sortable:           true
#                        filterable:         false
#                        show_filter:        false
#                    form:
#                        type:               choice
#                        block:              entity
#                        options:
#                            choices:        ['No', 'Yes']
#                            read_only:      true
#                            required:       false
#                            label:          "Is Extend Field"

                length:
                    options:
                        default_value:      255
                        required_property:
                            property_path:  extend.owner
                            value:          Custom
                    form:
                        type:               text
                        options:
                            required:       false
                            label:          'Length'
                            allowed_type:   'string'
                            block:          entity
                            subblock:       properties

                precision:
                    options:
                        default_value:      2
                        required_property:
                            property_path:  extend.owner
                            value:          Custom
                    form:
                        type:               text
                        options:
                            required:       false
                            label:          'Precision'
                            allowed_type:   'decimal'
                            block:          entity
                            subblock:       properties

                scale:
                    options:
                        default_value:      2
                        required_property:
                            property_path:  extend.owner
                            value:          Custom
                    form:
                        type:               text
                        options:
                            required:       false
                            label:          'Scale'
                            allowed_type:   'decimal'
                            block:          entity
                            subblock:       properties
