parameters:
    oro_entity_extend.dictionary_filter.class:    Oro\Bundle\EntityExtendBundle\Filter\DictionaryFilter
    oro_entity_extend.enum_filter.class:          Oro\Bundle\EntityExtendBundle\Filter\EnumFilter
    oro_entity_extend.multi_enum_filter.class:    Oro\Bundle\EntityExtendBundle\Filter\MultiEnumFilter

services:
    oro_entity_extend.dictionary_filter:
        class: %oro_entity_extend.dictionary_filter.class%
        arguments:
            - @form.factory
            - @oro_filter.filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: dictionary }

    oro_entity_extend.enum_filter:
        class: %oro_entity_extend.enum_filter.class%
        arguments:
            - @form.factory
            - @oro_filter.filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: enum }

    oro_entity_extend.multi_enum_filter:
        class: %oro_entity_extend.multi_enum_filter.class%
        arguments:
            - @form.factory
            - @oro_filter.filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: multi_enum }
