parameters:
    oro_entity_extend.type.target.class:                        Oro\Bundle\EntityExtendBundle\Form\Type\TargetType

services:
    oro_entity_extend.type.target:
        class:                                                  %oro_entity_extend.type.target.class%
        arguments:
            - @oro_entity_config.config_manager

        tags:
            - { name: form.type, alias: oro_entity_target_type }