placeholders:
    scripts_before:
        items:
            filter_templates_entity_extend:
                order: 7
            filter_embedded_templates_entity_extend:
                order: 8

items:
   filter_templates_entity_extend:
        template: OroEntityExtendBundle:Js:default_templates.js.twig
   filter_embedded_templates_entity_extend:
        template: OroEntityExtendBundle:Js:embedded_templates.js.twig
