parameters:
    oro_entity_extend.extend.extend_manager.class:          Oro\Bundle\EntityExtendBundle\Extend\ExtendManager
    oro_entity_extend.listener.doctrine_subscriber.class:   Oro\Bundle\EntityExtendBundle\EventListener\DoctrineSubscriber
    oro_entity_extend.listener.config_subscriber.class:     Oro\Bundle\EntityExtendBundle\EventListener\ConfigSubscriber
    oro_entity_extend.tools.schema.class:                   Oro\Bundle\EntityExtendBundle\Tools\Schema

services:
    oro_entity_extend.extend.extend_manager:
        class:                                              %oro_entity_extend.extend.extend_manager.class%
        arguments:                                          [@oro_entity_config.proxy.entity_manager, @oro_entity_extend.config.extend_config_provider, %oro_entity_extend.backend%, %kernel.root_dir%/entities]

    oro_entity_extend.config.extend_config_provider:
        tags:
            - { name: oro_entity_config.provider, scope: extend }

    oro_entity_extend.tools.schema:
        class:                                              %oro_entity_extend.tools.schema.class%
        arguments:                                          [@doctrine.orm.default_entity_manager, %oro_entity_extend.backend%]

    oro_entity_extend.listener.doctrine_subscriber:
        class:                                              %oro_entity_extend.listener.doctrine_subscriber.class%
        arguments:                                          [@oro_entity_extend.extend.extend_manager]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    oro_entity_extend.listener.config_subscriber:
        class:                                              %oro_entity_extend.listener.config_subscriber.class%
        arguments:                                          [@oro_entity_extend.extend.extend_manager, @oro_entity_extend.metadata.annotation_metadata_factory]
        tags:
            - { name: kernel.event_subscriber}
