parameters:
    oro_entity_extend.entity.cache.warmer.class:            Oro\Bundle\EntityExtendBundle\Cache\EntityCacheWarmer
    oro_entity_extend.extension.extend_entity.class:        Oro\Bundle\EntityExtendBundle\Form\Extension\ExtendEntityExtension
    oro_entity_extend.tools.dumper.class:                   Oro\Bundle\EntityExtendBundle\Tools\ExtendConfigDumper
    oro_entity_extend.listener.config_subscriber.class:     Oro\Bundle\EntityExtendBundle\EventListener\ConfigSubscriber
    oro_entity_extend.listener.entity_subscriber.class:     Oro\Bundle\EntityExtendBundle\EventListener\DoctrineSubscriber
    oro_entity_extend.twig.view_extension.class:            Oro\Bundle\EntityExtendBundle\Twig\ViewExtension
    oro_entity_extend.db_id_name_generator.class:           Oro\Bundle\EntityExtendBundle\Tools\DatabaseIdentifierNameGenerator
    oro_entity_extend.migration.config_processor.class:     Oro\Bundle\EntityExtendBundle\Migration\ExtendConfigProcessor
    oro_entity_extend.migration.post_up.listener.class:     Oro\Bundle\EntityExtendBundle\EventListener\PostUpMigrationListener
    oro_entity_extend.migration.options_manager.class:      Oro\Bundle\EntityExtendBundle\Migration\ExtendOptionsManager
    oro_entity_extend.migration.extension.extend.class:     Oro\Bundle\EntityExtendBundle\Migration\Extension\ExtendExtension

services:
    oro_entity_extend.entity.cache.warmer:
        public: false
        class: %oro_entity_extend.entity.cache.warmer.class%
        arguments:
            - @oro_entity_extend.tools.dumper
        tags:
            - { name: kernel.cache_warmer,  priority: 30 }

    oro_entity_extend.extension.extend_entity:
        class: %oro_entity_extend.extension.extend_entity.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type_extension, alias: form }

    oro_entity_extend.tools.dumper:
        class: %oro_entity_extend.tools.dumper.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %kernel.cache_dir%

    oro_entity_extend.listener.config_subscriber:
        class: %oro_entity_extend.listener.config_subscriber.class%
        arguments:
            - @oro_entity_config.provider.extend
        tags:
            - { name: kernel.event_subscriber}

    oro_entity_extend.listener.entity_subscriber:
        class: %oro_entity_extend.listener.entity_subscriber.class%
        arguments:
            - @oro_entity_extend.db_id_name_generator
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    oro_entity_extend.db_id_name_generator:
        class: %oro_entity_extend.db_id_name_generator.class%

    oro_entity_extend.migration.config_processor:
        class: %oro_entity_extend.migration.config_processor.class%
        arguments:
            - @oro_entity_config.config_manager

    oro_entity_extend.migration.post_up.listener:
        class: %oro_entity_extend.migration.post_up.listener.class%
        arguments:
            - @oro_entity_extend.migration.config_processor
            - @oro_entity_extend.tools.dumper
        tags:
            - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp, priority: -100 }

    oro_entity_extend.migration.options_manager:
        class: %oro_entity_extend.migration.options_manager.class%
        arguments:
            - @oro_entity.orm.entity_class_resolver

    oro_entity_extend.migration.extension.extend:
        class: %oro_entity_extend.migration.extension.extend.class%
        arguments:
            - @oro_entity_extend.migration.options_manager
